apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    metrics-infra: heapster
    name: heapster
  name: heapster
  namespace: openshift-infra
spec:
  replicas: 1
  selector:
    name: heapster
  template:
    metadata:
      labels:
        metrics-infra: heapster
        name: heapster
    spec:
      containers:
      - command:
        - heapster-wrapper.sh
        - --source=kubernetes.summary_api:https://kubernetes.default.svc:443?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
        - --tls_cert=/heapster-certs/tls.crt
        - --tls_key=/heapster-certs/tls.key
        - --tls_client_ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --allowed_users=system:master-proxy
        - --metric_resolution=30s
        - --v=10
        env:
        - name: STARTUP_TIMEOUT
          value: "500"
        image: openshift/origin-metrics-heapster:latest
        name: heapster
        ports:
        - containerPort: 8082
          name: http-endpoint
          protocol: TCP
        volumeMounts:
        - mountPath: /heapster-certs
          name: heapster-certs
      serviceAccount: heapster
      serviceAccountName: heapster
      volumes:
      - name: heapster-certs
        secret:
          defaultMode: 420
          secretName: heapster-certs
