#!/bin/bash
set -e

PROJ=${OPENSHIFT_VARIANT:-origin}

export PATH="/atomic/${PROJ}/_output/local/bin/linux/amd64/:${PATH}"

case "$1" in
    help )
        echo "run-origin [api|controllers|master|node|write-config|all] [OPTIONS...]"
        echo ""
        echo "    Running with no command is equivalent to 'all'."
        echo "    This will configure origin to use /${PROJ}.config, /${PROJ}.etcd, and /${PROJ}.volumes "
        echo "    for configuration, etcd storage, and volumes, respectively."
        echo "    Running 'all' will automatically invoke 'write-config' if /${PROJ}.config is missing."
        exit 0
        ;;
    api )
        shift
        exec openshift start master api --config=/${PROJ}.config/master/master-config.yaml "$@"
        ;;
    controllers )
        shift
        exec openshift start master controllers --config=/${PROJ}.config/master/master-config.yaml "$@"
        ;;
    master )
        shift
        exec openshift start master --config=/${PROJ}.config/master/master-config.yaml "$@"
        ;;
    etcd )
        shift
        exec openshift start etcd --config=/${PROJ}.config/master/master-config.yaml "$@"
        ;;
    node )
        shift
        systemctl start openvswitch
        exec openshift start node --config=/${PROJ}.config/node-$(hostname -f)/node-config.yaml "$@"
        ;;
    write-config )
        shift
        openshift start --write-config=/${PROJ}.config --etcd-dir=/${PROJ}.etcd --volume-dir=/${PROJ}.volumes "$@"
        exit $res
        ;;
    all )
        shift
        ;&
    * )
        # write config if this is the first time
        if [[ ! -e /${PROJ}.config ]]; then
            openshift start --write-config=/${PROJ}.config --etcd-dir=/${PROJ}.etcd --volume-dir=/${PROJ}.volumes "$@"
        fi

        systemctl start openvswitch
        exec openshift start --master-config=/${PROJ}.config/master/master-config.yaml --node-config=/${PROJ}.config/node-192.168.230.61/node-config.yaml "$@"
        ;;
esac

